### PR TITLE
Coveralls by token

### PR DESCRIPTION
**Pull request by liamhuber**
Still just trying to get coveralls to authenticate. I've added the COVERALLS_REPO_TOKEN to the secrets and here I try to invoke that directly

### CODE REVIEW

**Comment by liamhuber** [comment]
This hit exactly the same error.

One thing I do notice is that I'm installing `coveralls                         1.8.0  py_0                     conda-forge/noarch        13kB`; on the [conda-forge page](https://anaconda.org/conda-forge/coveralls) the most up-to-date no-arch is now at 3.3.1. There are known issues with authentification in a sticky issue on their [github repo](), but actually this issue is somewhat newer than v1.8.0 (which is 4 years old, while the issue is <3 years old), and my error message is different. This would explain why none of the solutions there helped.

What version is pyiron_base (or other repos where coverage is working) using? Yeah, base is installing 3.3.1

I'm going to try simply pinning the coveralls version over in a new branch on pyiron/actions, and then referencing that branch.

**Comment by jan-janssen** [comment]
For consistency it would still be great to use the file based version.

**Comment by liamhuber** [comment]
> For consistency it would still be great to use the file based version.

If you mean the one where we store the token in plain text in a file in the repo, then I disagree.

**Comment by liamhuber** [comment]
I'd like to get this running in a way that is compliant with the [coveralls docs](https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support)

**Comment by jan-janssen** [comment]
> Yes, consistency is nice. Once I manage to get this working the "right" way here, we can eventually make it the right way everywhere.

That would be great - in particular also integrating the `pyiron/actions` to the other repositories to have the same CI interface for all repositories would be a great next step.

**Pull request merged**
